name: Test Minimal

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Solo un echo
        run: echo "Hola desde GitHub Actions"